### PR TITLE
FACES-2816 Develop tests for the Button/Link category of the Liferay Faces Showcase

### PR DESCRIPTION
**Pull request by stiemannkj1**

### CODE REVIEW

**Comment by stiemannkj1** [comment]
@ngriffin7a,
Please note that there are two commits in this PR which need to be backported.

**Comment by ngriffin7a** [comment]
Merged and backported. Thank you.

**Comment by ngriffin7a** [comment]
@stiemannkj1 I only see one commit associated with FACES-2816 in the git log. Not sure what you mean by two commits in this PR?

Also, the backport https://github.com/liferay/liferay-faces-showcase/commit/5f6ee24b0c6ecce4466cc080f72dac336d0af712 had some trouble in the sense that many of the files under src/main/test show up as being "Added" rather than "Modified" like they are in the master branch. Perhaps I missed a backport and never added them previously? Please investigate. Thank you.

**Comment by stiemannkj1** [comment]
@ngriffin7a,
There are two commits: https://github.com/liferay/liferay-faces-showcase/pull/28/commits/780867aa6335c39167032a15513c7196a90a6453 and https://github.com/liferay/liferay-faces-showcase/pull/28/commits/4e4223a1b4d1978e65373bef01ab92233799e88a. I think Phil forgot to put FACES-2816 in the commit message for https://github.com/liferay/liferay-faces-showcase/pull/28/commits/780867aa6335c39167032a15513c7196a90a6453, but as you can see, it still says: "Develop tests for the Button/Link category of the Liferay Faces Showcase"

**Comment by stiemannkj1** [comment]
@ngriffin7a,
Although the commits weren't backported correctly, the files seem to be fine, so we don't need to worry about this.

**Comment by ngriffin7a** [comment]
OK thanks for doing the research.

**Pull request merged**
