### PR TITLE
FACES-3131 specify the collection type

### PR DESCRIPTION
**Pull request by vsingleton**

### CODE REVIEW

**Comment by ngriffin7a** [comment]
@vsingleton: According to convention, the `id` attribute always appears first, then alphabetical after that. Please fix/squash/push and let me know when it is ready again for review. Thanks. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by vsingleton** [comment]
@ngriffin7a The branches have been updated.

**Comment by ngriffin7a** [comment]
bp to 3.x and 2.x <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ngriffin7a** [comment]
Merged, thank you. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
