### PR TITLE
FACES-2948 Added tests for inputFile and inputTextarea of the Liferay Faces Showcase

### PR DESCRIPTION
**Pull request by stiemannkj1**

### CODE REVIEW

**Comment by stiemannkj1** [comment]
@ngriffin7a, there are two commits in this branch. Please make sure to backport both commits.

**Comment by ngriffin7a** [comment]
Merged and backported to 3.x and 2.x (but did not backport h:inputFile testers to 2.x). Thank you.

**Comment by stiemannkj1** [comment]
@ngriffin7a, feel free to remove the [**`pom.xml`** config](https://github.com/liferay/liferay-faces-showcase/commit/dbb889ecc022afe8c0d31914adcd1366b492b9ca#diff-94285b4fd0cd0a173fac8981305f3a1aR134) and [**`liferay-jsf-jersey.png`**](diff-44c55b3ce87f56a3ff0e3294ea7eecdf) from `2.x` as well since they were only included for file upload tests.

**Comment by ngriffin7a** [comment]
@stiemannkj1 done, thanks.

**Pull request closed without merging**
