### PR TITLE
FACES-3136 Setting required=true for h:inputFile, bridge:inputFile, or alloy:inputFile has no effect

### PR DESCRIPTION
**Pull request by stiemannkj1**

### CODE REVIEW

**Comment by ngriffin7a** [comment]
bp to 3.x and 2.x (but not inputFile.xhtml to 2.x) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ngriffin7a** [comment]
Should jsf-showcase-webapp/src/test/java/com/liferay/faces/test/showcase/inputfile/InputFileTester.java be present in 2.x? It currently is. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ngriffin7a** [comment]
Merged, thank you. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by stiemannkj1** [comment]
@ngriffin7a, yes **`jsf-showcase-webapp/src/test/java/com/liferay/faces/test/showcase/inputfile/InputFileTester.java`** should be preset in `2.x` only becuase `alloy:inputFile` and `bridge:inputFile` testers depend on it (it is not run for the jsf-showcase though).

**Pull request merged**
